version: '3.8'  
services:
  calculator:
    build: . 
    image: nancetech/compose-calculator-microservice:latest
    ports:
      - "4000:4000"
    volumes:
      - ./logs:/usr/src/logs
    environment:
      - NODE_ENV=production
    healthcheck:
      test: "curl http://localhost:4000"
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 60s
